version: '2'
services:
    jhipsterapp1-app:
        image: jhipsterapp1
        external_links:
            - jhipsterapp1-mysql:mysql
            - jhipsterapp1-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipsterapp1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterapp1-mysql:
        extends:
            file: mysql.yml
            service: jhipsterapp1-mysql
    jhipsterapp1-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterapp1-elasticsearch
